### ISSUE TITLE
Peer Review - Expanding 3.3 - Design Verification Plan: Checklist-Based Review

### ISSUE THREAD

**Issue by AhmedAl-Hayali** [emilyperica/ScoreGen#166]
**Artifact Under Review**
VnV Plan

**Team Number for Team Doing the Review**
Team 08

**Description of Issue**
The checklist provided under the `Checklist-Based Review` subsection of `3.3 - Design Verification Plan` is quite coarse, and may benefit from being itemized with more granularity, e.g.,
- Are the core algorithms well-suited for the required audio-to-sheet music conversion?
  - Identify a list of features, research a list of algorithms, do some tinkering, then test for whether the checklist is met or not.
  - [ ] Algorithm X extracts structured feature 1, e.g., pitch/rhythm (from FR-SP2), from unstructured data, e.g., `.WAV` or `.MP3` file (from FR-AR1-3-1).
  - [ ] Algorithm Y ... feature 2 ...
  - [ ] ...
- Are system constraints, e.g., processing time, memory usage, addressed in the design?
  - [ ] Subcomponent X, e.g., rhythm or pitch extraction algorithm, meets processing time requirements, e.g., <30s processing time for a 3.5Mb file.
  - [ ] Subcomponent X meets memory usage requirements, e.g., uses < 350Mb of RAM when processing a 3.5Mb file.
  - [ ] Subcomponent X meets storage requirements, e.g., produces an artifact smaller than 1.5Mb in size for a 3.5Mb input file.
  - [ ] Subcomponent Y ...
  - [ ] ...
- Is the design modular and maintainable?
  - [ ] Subcomponent X, e.g., the `MP3` reading module, exposes an abstract interface whose input is, e.g., an `MP3` file, and output, e.g., a bit-stream, is well-defined.
  - [ ] Subcomponent X has [cyclomatic complexity](https://radon.readthedocs.io/en/stable/intro.html#cyclomatic-complexity) less than 9. *Note: 9 is potentially a little unrealistic because a "subcomponent" may be composed of many (Python) modules, each of which likely has a cyclomatic complexity of 5 or more*.
  - [ ] Subcomponent Y ...
  - [ ] ...
